### ISSUE TITLE
mkrofs: fail to build with gcc 15.2.0

### ISSUE THREAD

**Issue by anglov** [phoenix-rtos/phoenix-rtos-project#1477]
# Description
ENV: Ubuntu 25.10, gcc (Ubuntu 15.2.0-4ubuntu4) 15.2.0

`TARGET=host-generic-pc ./phoenix-rtos-build/build.sh clean all`

ends with following error:

```
In function ‘basestrncpy’,
    inlined from ‘processDir’ at /home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:283:2:
/home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:30:23: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
   30 | #define LOG_prefix    "rofs: "
      |                       ^~~~~~~~
/home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:32:39: note: in expansion of macro ‘LOG_prefix’
   32 | #define ERR(fmt, ...) fprintf(stderr, LOG_prefix fmt "\n", ##__VA_ARGS__)
      |                                       ^~~~~~~~~~
/home/anglov/Project/code/phoenix-rtos-project/phoenix-rtos-hostutils/mkrofs/mkrofs.c:225:17: note: in expansion of macro ‘ERR’
  225 |                 ERR("Name '%s' will be trimmed to %zu characters", tmp, len);
      |                 ^~~
```

# Analysis

This issue is not reproducible during normal target build. It's due to fact, that sanitizers is not enabled then.

After looking at the compilation options it seems, that issue only occurs while:
- sanitizers are enabled
- optimization level is -O2 or higher (-Os and -Og doesn't trigger the issue)

Looking at documentation and glibc code, basename should always return non-null. So this code should have never null on %s format (tmp should never be null):
https://github.com/phoenix-rtos/phoenix-rtos-hostutils/blob/b7314da92486dd192dca228c25f8fc5cb5ce718f/mkrofs/mkrofs.c#L221
```c
(...)
	tmp = basename(strcpy((char *)common.buf, src));

	size_t tmplen = strlen(tmp);
	if (tmplen >= len) {
		ERR("Name '%s' will be trimmed to %zu characters", tmp, len);
		memcpy(dst, tmp, len);
	}
(...)
```
So I assume, that this error is gcc false-positive somehow connected with sanitizers and optimization.

# Possible sollution
I open that issue instead of making a PR mainly because not sure what is better.

I checked that explicit check on `tmp == NULL` will silent the error. But in theory this check is redundant, and not-null should be asserted by stdlib.

Another solution I see is to disable warning by the pragma. 

I have mixed feeling to both solution (first create redundancy, second involves compiler-dependent pragmas). I leave this issue to open discussion how we should workaround compiler false-positives, also in less critical code as we have here.
